apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-ovto
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-ovto
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-ovto
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-ovto
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-ovto
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dovf-tenant/nodejs-users/simple-nodejs-app-ovto@sha256:f52c7a2e4b9f7b922bebb09c227d33821e0c6fb231d5859aff11401035bb09a4
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
