apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: simple-nodejs-app-ovto
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dovf-tenant/nodejs-users/simple-nodejs-app-ovto@sha256:f52c7a2e4b9f7b922bebb09c227d33821e0c6fb231d5859aff11401035bb09a4
        name: my-nodejs
        resources: {}
status: {}
